#!/bin/bash

export KUBECONFIG=$HOME/.bluemix/plugins/container-service/clusters/bikeshare/kube-config-mil01-bikeshare.yml

APP=$1
VERSION=$2

kubectl set image deployments.apps $APP-deployment $APP=nimbostratuz/$APP:$VERSION
